services:
  - type: web
    name: alertoph
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_DEBUG
        value: "False"
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: OPENROUTESERVICE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
